version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "SnickerSec"
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "chore(deps):"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "SnickerSec"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(deps):"
